/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utspbodealer;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class customer extends javax.swing.JFrame {
public String idcustomer="";
    public Connection con;
    public ResultSet rs;
    public Statement stat;
    public String sql="";
    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        koneksidatabase db =new koneksidatabase();
        db.koneksidatabase();
        con=db.con;
        rs=db.rs;
        stat=db.stat;
        tabelcustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Talamat = new javax.swing.JTextField();
        Cid = new javax.swing.JComboBox<>();
        Tid = new javax.swing.JTextField();
        Tnama = new javax.swing.JTextField();
        EXIT = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelcustomer = new javax.swing.JTable();
        search = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dataservis = new javax.swing.JMenuItem();
        montir = new javax.swing.JMenuItem();
        motor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAPORAN DATA CUSTOMER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 530, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALAMAT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID CUSTOMER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA CUSTOMER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(Talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 150, 30));

        Cid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "M001", "M002", "M003", "M004", "M005", "N001", "N002", "N003", "N004", "N005" }));
        jPanel1.add(Cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 30));
        jPanel1.add(Tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 30));
        jPanel1.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 80, 40));

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 40));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 40));

        UPDATE.setText("UPDATE");
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, 40));

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel1.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 70, 40));

        tabelcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelcustomer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 357, 530, 120));

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 80, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 480));

        jMenu1.setText("Menu");

        dataservis.setText("data servis");
        dataservis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataservisActionPerformed(evt);
            }
        });
        jMenu1.add(dataservis);

        montir.setText("montir");
        montir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montirActionPerformed(evt);
            }
        });
        jMenu1.add(montir);

        motor.setText("motor");
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        jMenu1.add(motor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
try {
     sql ="insert into customer values('"+
             Cid.getSelectedItem()+"','"+
             Tnama.getText()+"','"+
             Talamat.getText()+"')";
         stat=con.createStatement();
            stat.execute(sql);
        Tid.setText("");
        Tnama.setText("");
        Talamat.setText("");
        JOptionPane.showMessageDialog(rootPane, "Data Telah Disimpan");
    } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan, Tidak dapat duplicate data");
        } 
      tabelcustomer();         // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void tabelcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelcustomerMouseClicked
Tid.setText(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 0).toString());
        Tnama.setText(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 1).toString());
        Talamat.setText(tabelcustomer.getValueAt(tabelcustomer.getSelectedRow(), 2).toString());   
        Tid.setVisible(true);
        Cid.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_tabelcustomerMouseClicked

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
 try {
            sql="delete from customer where idcustomer='"+
                      Tid.getText()+"'";
            stat=con.createStatement();
            stat.execute(sql);
            Tid.setText("");
             Cid.setVisible(true);
            Tid.setVisible(true);
            Cid.setSelectedIndex(0);
            Tid.setText("");
             Tnama.setText("");
             Talamat.setText("");
            JOptionPane.showMessageDialog(rootPane, "data telah dihapus");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Dihapus"+e);
        }
             tabelcustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
  Tid.setText("");
        Tnama.setText("");
        Talamat.setText("");
Cid.setSelectedIndex(0);    
Cid.setVisible(true);
Tid.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_RESETActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
try {
            sql="select * from customer where idcustomer='"+
            Cid.getSelectedItem()+"'";
            stat=con.createStatement();
            rs=stat.executeQuery(sql);
            if (rs.next()) {
                Tid.setText(rs.getString("idcustomer"));
                Tnama.setText(rs.getString("namacustomer"));
                Talamat.setText(rs.getString("alamat"));
                 Cid.setVisible(false);
                Tid.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "ini data nya");
            }else {
                Cid.setVisible(true);
                Tid.setVisible(false);
                Cid.setSelectedIndex(0);
                Tid.setText("");
                Tnama.setText("");
                Tid.setText("");
                 Cid.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "data belum di input");
            }
        }    
      catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "error" +e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void dataservisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataservisActionPerformed
 dataservis project = new dataservis(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_dataservisActionPerformed

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
     motor project = new motor(); 
  project.setVisible(true);
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    private void montirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montirActionPerformed
 montir project = new montir(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_montirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cid;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField Talamat;
    private javax.swing.JTextField Tid;
    private javax.swing.JTextField Tnama;
    private javax.swing.JButton UPDATE;
    private javax.swing.JMenuItem dataservis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem montir;
    private javax.swing.JMenuItem motor;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelcustomer;
    // End of variables declaration//GEN-END:variables

    private void tabelcustomer() {
       DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Id Customer");
        tabel.addColumn("Nama Customer");
        tabel.addColumn("Alamat");
        
        try {
            sql="select * from customer";
            stat= con.createStatement();
            rs= stat.executeQuery(sql);
            while (rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2),
                    rs.getString(3),  
                });
                tabelcustomer.setModel(tabel);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error"+e);
        } 
    }
}
