/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utspbodealer;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class montir extends javax.swing.JFrame {
 public String kode_montir="";
    public Connection con;
    public ResultSet rs;
    public Statement stat;
    public String sql="";
    /**
     * Creates new form montir
     */
    public montir() {
        initComponents();
        koneksidatabase db =new koneksidatabase();
        db.koneksidatabase();
        con=db.con;
        rs=db.rs;
        stat=db.stat;
        tabelmontir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        telp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        kodemontir = new javax.swing.JLabel();
        namamontir = new javax.swing.JLabel();
        Ttelp = new javax.swing.JTextField();
        Ckode = new javax.swing.JComboBox<>();
        Tnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmontir = new javax.swing.JTable();
        Tkode = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dataservis = new javax.swing.JMenuItem();
        customer = new javax.swing.JMenuItem();
        motor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telp.setText("TELP");
        jPanel1.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, -1));

        kodemontir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodemontir.setText("KODE MONTIR");
        jPanel1.add(kodemontir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        namamontir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namamontir.setText("NAMA MONTIR");
        jPanel1.add(namamontir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel1.add(Ttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 170, 30));

        Ckode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "J001", "J002", "J003", "J004", "J005", "K001", "K002", "K003", "K004", "K005" }));
        Ckode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkodeActionPerformed(evt);
            }
        });
        jPanel1.add(Ckode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, 30));
        jPanel1.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LAPORAN DATA MONTIR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 210, -1));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 70, 40));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 40));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 70, 40));

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 80, 40));

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 80, 40));

        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 80, 40));

        tabelmontir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmontir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmontirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmontir);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 510, 130));
        jPanel1.add(Tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 530));

        jMenu1.setText("Menu");

        dataservis.setText("data servis");
        dataservis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataservisActionPerformed(evt);
            }
        });
        jMenu1.add(dataservis);

        customer.setText("customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jMenu1.add(customer);

        motor.setText("motor");
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });
        jMenu1.add(motor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void tabelmontirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmontirMouseClicked
Tkode.setText(tabelmontir.getValueAt(tabelmontir.getSelectedRow(), 0).toString());
        Tnama.setText(tabelmontir.getValueAt(tabelmontir.getSelectedRow(), 1).toString());
        Ttelp.setText(tabelmontir.getValueAt(tabelmontir.getSelectedRow(), 2).toString());  
        Tkode.setVisible(true);
        Ckode.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_tabelmontirMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
try {
     sql ="insert into tbmontir values('"+
             Ckode.getSelectedItem()+"','"+
             Tnama.getText()+"','"+
             Ttelp.getText()+"')";
         stat=con.createStatement();
            stat.execute(sql);
        Ckode.setSelectedIndex(0);
        Tnama.setText("");
        Ttelp.setText("");
        JOptionPane.showMessageDialog(rootPane, "Data Telah Disimpan");
    } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan, Tidak dapat duplicate data");
        } 
      tabelmontir();            // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
try {
            sql="delete from tbmontir where kodemontir='"+
                      Tkode.getText()+"'";
            stat=con.createStatement();
            stat.execute(sql);
            Tkode.setText("");
             Ckode.setVisible(true);
            Tkode.setVisible(false);
            Ckode.setSelectedIndex(0);
            Tkode.setText("");
             Tnama.setText("");
             Ttelp.setText("");
            JOptionPane.showMessageDialog(rootPane, "data telah dihapus");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Dihapus"+e);
        }
             tabelmontir();         // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void CkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkodeActionPerformed
kode_montir = (String) Ckode.getSelectedItem();
        if (kode_montir == "J001"){
            Tnama.  setText ("Rafael");
            Ttelp. setText("085398582504");
        }
        
        else if (kode_montir == "J002"){
            Tnama.  setText ("Gerry");
             Ttelp. setText("085387483692");
        }
        
        else if (kode_montir == "J003"){
            Tnama.  setText ("Jonathan");
             Ttelp. setText("085365730818");
        }

        else if (kode_montir == "J004"){
            Tnama.  setText ("Frizzy");
             Ttelp. setText("085390858901");
        }
        
        else if (kode_montir == "J005"){
            Tnama.  setText ("Marco");
             Ttelp. setText("085267982491");
        }
        
        else if (kode_montir == "K001"){
            Tnama.  setText ("Bilbo");
             Ttelp. setText("082378468306");
        }
        
        else if (kode_montir == "K002"){
            Tnama.  setText ("Theoria");  
             Ttelp. setText("081367519721");
        }
        
        else if (kode_montir == "K003"){
            Tnama.  setText ("Ricky");
             Ttelp. setText("083423085124");
        }
        
        else if (kode_montir == "K004"){
            Tnama.  setText ("Richard");
             Ttelp. setText("081287871241");
        }
        
        else if (kode_montir == "K005"){
            Tnama.  setText ("Fernando");
             Ttelp. setText("086386861284");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_CkodeActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
try {
    sql="update tbmontir set namamontir='"+
        Tnama.getText()+"',telp='"+
        Ttelp.getText()+"' where kodemontir='"+
            Tkode.getText()+"'";
  stat=con.createStatement();
  stat.execute(sql);
            
  JOptionPane.showMessageDialog(rootPane, "data telah di edit");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "data gagal di edit"+e);
        }
        tabelmontir();         // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
 Ckode.setSelectedIndex(0);
        Tnama.setText("");
        Ttelp.setText("");
Ckode.setVisible(true);
Tkode.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
try {
            sql="select * from tbmontir where kodemontir='"+
            Ckode.getSelectedItem()+"'";
            stat=con.createStatement();
            rs=stat.executeQuery(sql);
            if (rs.next()) {
                Tkode.setText(rs.getString("kodemontir"));
                Tnama.setText(rs.getString("namamontir"));
                Ttelp.setText(rs.getString("telp"));
                 Ckode.setVisible(false);
                Tkode.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "ini data nya");
            }else {
                Ckode.setVisible(true);
                Tkode.setVisible(false);
                Ckode.setSelectedIndex(0);
                Tkode.setText("");
                Tnama.setText("");
                Ttelp.setText("");
                 Ckode.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "data belum di input");
            }
        }    
      catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "error" +e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void dataservisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataservisActionPerformed
 dataservis project = new dataservis(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_dataservisActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
 customer project = new customer(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
 motor project = new motor(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_motorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(montir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(montir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(montir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(montir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new montir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ckode;
    private javax.swing.JTextField Tkode;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Ttelp;
    private javax.swing.JMenuItem customer;
    private javax.swing.JMenuItem dataservis;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kodemontir;
    private javax.swing.JMenuItem motor;
    private javax.swing.JLabel namamontir;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabelmontir;
    private javax.swing.JLabel telp;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void tabelmontir() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Kode Montir");
        tabel.addColumn("Nama Montir");
        tabel.addColumn("Telepon");
        
        try {
            sql="select * from tbmontir";
            stat= con.createStatement();
            rs= stat.executeQuery(sql);
            while (rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2),
                    rs.getString(3),  
                });
                tabelmontir.setModel(tabel);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error"+e);
        }
    }
}
