/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utspbodealer;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class motor extends javax.swing.JFrame {
public String noplat="";
    public Connection con;
    public ResultSet rs;
    public Statement stat;
    public String sql="";
    /**
     * Creates new form motor
     */
    public motor() {
        initComponents();
        koneksidatabase db =new koneksidatabase();
        db.koneksidatabase();
        con=db.con;
        rs=db.rs;
        stat=db.stat;
        tabelmotor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LAPORANDATAMOTOR = new javax.swing.JLabel();
        NOPLAT = new javax.swing.JLabel();
        NORANGKA = new javax.swing.JLabel();
        TIPE = new javax.swing.JLabel();
        Ctipe = new javax.swing.JComboBox<>();
        Tplat = new javax.swing.JTextField();
        Trangka = new javax.swing.JTextField();
        SAVE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmotor = new javax.swing.JTable();
        Ttipe = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dataservis = new javax.swing.JMenuItem();
        customer = new javax.swing.JMenuItem();
        montir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 470, -1));

        LAPORANDATAMOTOR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LAPORANDATAMOTOR.setText("LAPORAN DATA MOTOR");
        jPanel1.add(LAPORANDATAMOTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        NOPLAT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NOPLAT.setText("NO PLAT");
        jPanel1.add(NOPLAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 20));

        NORANGKA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NORANGKA.setText("NO RANGKA");
        jPanel1.add(NORANGKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        TIPE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TIPE.setText("TIPE");
        jPanel1.add(TIPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        Ctipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "REVO", "SCOOPY", "VARIO", "PCX", "SUPRA X", "BEAT" }));
        Ctipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtipeActionPerformed(evt);
            }
        });
        jPanel1.add(Ctipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 30));
        jPanel1.add(Tplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 30));
        jPanel1.add(Trangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 30));

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 50));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 70, 50));

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 50));

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel1.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 50));

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 60, 50));

        tabelmotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelmotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelmotorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelmotor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 470, 110));
        jPanel1.add(Ttipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        jMenu1.setText("Menu");

        dataservis.setText("data servis");
        dataservis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataservisActionPerformed(evt);
            }
        });
        jMenu1.add(dataservis);

        customer.setText("customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jMenu1.add(customer);

        montir.setText("montir");
        montir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montirActionPerformed(evt);
            }
        });
        jMenu1.add(montir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Laporan");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelmotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelmotorMouseClicked
Tplat.setText(tabelmotor.getValueAt(tabelmotor.getSelectedRow(), 0).toString());
        Trangka.setText(tabelmotor.getValueAt(tabelmotor.getSelectedRow(), 1).toString());
        Ttipe.setText(tabelmotor.getValueAt(tabelmotor.getSelectedRow(), 2).toString());  
        Ttipe.setVisible(true);
        Ctipe.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_tabelmotorMouseClicked

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
try {
     sql ="insert into tbmotor values('"+
             Tplat.getText()+"','"+
             Trangka.getText()+"','"+
             Ctipe.getSelectedItem()+"')";
         stat=con.createStatement();
            stat.execute(sql);
        Tplat.setText("");
        Trangka.setText("");
        Ctipe.setSelectedIndex(0);
        JOptionPane.showMessageDialog(rootPane, "Data Telah Disimpan");
    } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan, Tidak dapat duplicate data");
        } 
      tabelmotor();        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
Tplat.setText("");
        Trangka.setText("");
        Ttipe.setText("");
        Ctipe.setSelectedIndex(0);
        Ctipe.setVisible(true);
Ttipe.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_RESETActionPerformed

    private void CtipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CtipeActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
try {
            sql="delete from tbmotor where noplat='"+
                      Tplat.getText()+"'";
            stat=con.createStatement();
            stat.execute(sql);
            Tplat.setText("");
             Ctipe.setVisible(true);
            Ttipe.setVisible(false);
            Ctipe.setSelectedIndex(0);
            Tplat.setText("");
             Trangka.setText("");
             Ttipe.setText("");
            JOptionPane.showMessageDialog(rootPane, "data telah dihapus");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Dihapus"+e);
        }
             tabelmotor();        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
try {
    sql="update tbmotor set norangka='"+
        Trangka.getText()+"',tipe='"+
        Ttipe.getText()+"' where noplat='"+
            Tplat.getText()+"'";
  stat=con.createStatement();
  stat.execute(sql);
            
  JOptionPane.showMessageDialog(rootPane, "data telah di edit");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "data gagal di edit"+e);
        }
        tabelmotor();        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
 customer project = new customer(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void dataservisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataservisActionPerformed
 dataservis project = new dataservis(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_dataservisActionPerformed

    private void montirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montirActionPerformed
 montir project = new montir(); 
  project.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_montirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(motor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new motor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ctipe;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel LAPORANDATAMOTOR;
    private javax.swing.JLabel NOPLAT;
    private javax.swing.JLabel NORANGKA;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel TIPE;
    private javax.swing.JTextField Tplat;
    private javax.swing.JTextField Trangka;
    private javax.swing.JTextField Ttipe;
    private javax.swing.JButton UPDATE;
    private javax.swing.JMenuItem customer;
    private javax.swing.JMenuItem dataservis;
    private javax.swing.JButton exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem montir;
    private javax.swing.JTable tabelmotor;
    // End of variables declaration//GEN-END:variables

    private void tabelmotor() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("No Plat");
        tabel.addColumn("No Rangka");
        tabel.addColumn("Tipe");
        
        try {
            sql="select * from tbmotor";
            stat= con.createStatement();
            rs= stat.executeQuery(sql);
            while (rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2),
                    rs.getString(3),  
                });
                tabelmotor.setModel(tabel);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error"+e);
        } 
    }
}
