/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajar;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class barang extends javax.swing.JFrame {
    public String kode_barang="";
    public Connection con;
    public ResultSet rs;
    public Statement stat;
    public String sql="";

    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
           koneksi db =new koneksi();
        db.koneksi();
        con=db.con;
        rs=db.rs;
        stat=db.stat;
        tampiltabelbarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        databarang = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        harga = new javax.swing.JLabel();
        kodebarang = new javax.swing.JLabel();
        satuan = new javax.swing.JLabel();
        stok = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        Ckode = new javax.swing.JComboBox<>();
        Tkode = new javax.swing.JTextField();
        Tnama = new javax.swing.JTextField();
        Tstok = new javax.swing.JTextField();
        Tharga = new javax.swing.JTextField();
        Csatuan = new javax.swing.JComboBox<>();
        Tsatuan = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        cari = new javax.swing.JLabel();
        Cdata = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        databarang.setText("LAPORAN DATA BARANG");
        jPanel1.add(databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, -1));

        harga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("HARGA");
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        kodebarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodebarang.setForeground(new java.awt.Color(255, 255, 255));
        kodebarang.setText("KODE BARANG");
        jPanel1.add(kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        satuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        satuan.setForeground(new java.awt.Color(255, 255, 255));
        satuan.setText("SATUAN");
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        stok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stok.setForeground(new java.awt.Color(255, 255, 255));
        stok.setText("STOK");
        jPanel1.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, -1));

        namabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namabarang.setForeground(new java.awt.Color(255, 255, 255));
        namabarang.setText("NAMA BARANG");
        jPanel1.add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        Ckode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "A01", "A02", "A03", "A04", "A05", "B01", "B02", "B03", "B04", "B05", "C01", "C02", "C03", "C04", "C05" }));
        Ckode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CkodeActionPerformed(evt);
            }
        });
        jPanel1.add(Ckode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 30));

        Tkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TkodeActionPerformed(evt);
            }
        });
        jPanel1.add(Tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 30));
        jPanel1.add(Tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 200, 30));
        jPanel1.add(Tstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 30));
        jPanel1.add(Tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 200, 30));

        Csatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Unit", "Kg ", "Dus ", "Liter" }));
        jPanel1.add(Csatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, 30));
        jPanel1.add(Tsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, 30));

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 80, 40));

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 40));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 80, 40));

        EDIT.setText("UPDATE");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });
        jPanel1.add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, 40));

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel1.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 70, 40));

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 70, 40));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        tabelbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelbarangKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelbarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 600, 150));

        cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setText("CARI DATA");
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 70, -1));

        Cdata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "A01", "A02", "A03", "A04", "A05", "B01", "B02", "B03", "B04", "B05", "C01", "C02", "C03", "C04", "C05" }));
        jPanel1.add(Cdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 200, 30));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 70, 40));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Pictures\\barang.jpg")); // NOI18N
        background.setLabelFor(background);
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        try {
            sql="delete from barang where stok='"+
                      Tstok.getText()+"'";
            stat=con.createStatement();
            stat.execute(sql);
             Ckode.setVisible(true);
            Tkode.setVisible(false);
            Ckode.setSelectedIndex(0);
            Tnama.setText("");
             Tharga.setText("");
             Csatuan.setVisible(true);
             Tsatuan.setVisible(false);
              Csatuan.setSelectedIndex(0);
               Tstok.setText("");
            JOptionPane.showMessageDialog(rootPane, "data telah dihapus");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Dihapus"+e);
        }
             tampiltabelbarang();        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
  try {
            sql="select * from barang where kode_barang='"+
            Cdata.getSelectedItem()+"'";
            stat=con.createStatement();
            rs=stat.executeQuery(sql);
            if (rs.next()) {
                Tkode.setText(rs.getString("kode_barang"));
                Tnama.setText(rs.getString("nama_barang"));
                Tharga.setText(rs.getString("harga"));
                Tsatuan.setText(rs.getString("satuan"));
                Tstok.setText(rs.getString("stok"));
                 Ckode.setVisible(false);
                Tkode.setVisible(true);
                Csatuan.setVisible(false);
                Tsatuan.setVisible(true);
                JOptionPane.showMessageDialog(rootPane, "ini data nya");
            }else {
                Ckode.setVisible(true);
                Tkode.setVisible(false);
                Ckode.setSelectedIndex(0);
                Tnama.setText("");
                Tharga.setText("");
                Tstok.setText("");
                 Cdata.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "data belum di input");
            }
        }    
      catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "error" +e);
        }
    }//GEN-LAST:event_SEARCHActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
       Tkode.setText(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 0).toString());
        Tnama.setText(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 1).toString());
        Tharga.setText(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 2).toString());
        Tsatuan.setText(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 3).toString());
        Tstok.setText(tabelbarang.getValueAt(tabelbarang.getSelectedRow(), 4).toString());
        Ckode.setVisible(false);
        Tkode.setVisible(true);
        Csatuan.setVisible(false);
        Tsatuan.setVisible(true);
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
    try {
     sql ="insert into barang values('"+
             Ckode.getSelectedItem()+"','"+
        Tnama.getText()+"','"+
        Tharga.getText()+"','"+
        Csatuan.getSelectedItem()+"','"+
        Tstok.getText()+"')";  
         stat=con.createStatement();
            stat.execute(sql);
        JOptionPane.showMessageDialog(rootPane, "Data Telah Disimpan");
    } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan, Tidak dapat duplicate data");
        } 
      tampiltabelbarang(); // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void TkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TkodeActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
 Tkode.setText("");
        Tnama.setText("");
        Tharga.setText("");
        Tsatuan.setText("");
        Csatuan.setSelectedIndex(0);
        Tstok.setText(""); 
        Ckode.setSelectedIndex(0);
        Cdata.setSelectedIndex(0);
Tkode.setVisible(false);
        Ckode.setVisible(true);
Tsatuan.setVisible(false);
Csatuan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_RESETActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
      try {
    sql="update barang set nama_barang='"+
        Tnama.getText()+"',harga='"+
        Tharga.getText()+"',satuan='"+
        Tsatuan.getText()+"',stok='"+
        Tstok.getText()+"' where kode_barang='"+
        Tkode.getText()+"'";
  stat=con.createStatement();
  stat.execute(sql);
            
  JOptionPane.showMessageDialog(rootPane, "data telah di edit");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, "data gagal di edit"+e);
        }
        tampiltabelbarang();        // TODO add your handling code here:
    }//GEN-LAST:event_EDITActionPerformed

    private void tabelbarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelbarangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelbarangKeyPressed

    private void CkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CkodeActionPerformed
     kode_barang = (String) Ckode.getSelectedItem();
        if (kode_barang == "A01"){
            Tnama.  setText ("KOMPOR");
            Tharga. setText("100000");
        }
        
        else if (kode_barang == "A02"){
            Tnama.  setText ("KULKAS");
            Tharga. setText("23000000");
        }
        
        else if (kode_barang == "A03"){
            Tnama.  setText ("AC");
            Tharga. setText("3500000");
           
        }

        else if (kode_barang == "A04"){
            Tnama.  setText ("SPEAKER");
            Tharga. setText("834000");
        }
        
        else if (kode_barang == "A05"){
            Tnama.  setText ("LAMPU HIAS");
            Tharga. setText("15000000");
        }
        
        else if (kode_barang == "B01"){
            Tnama.  setText ("DISPENSER");
            Tharga. setText("1500000");
        }
        
        else if (kode_barang == "B02"){
            Tnama.  setText ("RICE COOKER");
            Tharga. setText("1200000");  
        }
        
        else if (kode_barang == "B03"){
            Tnama.  setText ("KARPET");
            Tharga. setText("150000");
        }
        
        else if (kode_barang == "B04"){
            Tnama.  setText ("BLENDER");
            Tharga. setText("250000");
        }
        
        else if (kode_barang == "B05"){
            Tnama.  setText ("PIRING");
            Tharga. setText("350000");
        }
        else if (kode_barang == "C01"){
            Tnama.  setText ("GELAS");
            Tharga. setText("400000");
        }   
        else if (kode_barang == "C02"){
            Tnama.  setText ("TV");
            Tharga. setText("6450000");
        }   
        else if (kode_barang == "C03"){
            Tnama.  setText ("BED");
            Tharga. setText("18000000");
        }   
        else if (kode_barang == "C04"){
            Tnama.  setText ("SOFA BED");
            Tharga. setText("12400000");
        }
        else if (kode_barang == "C05"){
            Tnama.  setText ("MESIN CUCI");
            Tharga. setText("45600000");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_CkodeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    admin project = new admin();
    project.setVisible(true); 
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new barang().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cdata;
    private javax.swing.JComboBox<String> Ckode;
    private javax.swing.JComboBox<String> Csatuan;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField Tharga;
    private javax.swing.JTextField Tkode;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tsatuan;
    private javax.swing.JTextField Tstok;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cari;
    private javax.swing.JLabel databarang;
    private javax.swing.JLabel harga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kodebarang;
    private javax.swing.JLabel namabarang;
    private javax.swing.JLabel satuan;
    private javax.swing.JLabel stok;
    private javax.swing.JTable tabelbarang;
    // End of variables declaration//GEN-END:variables

    private void tampiltabelbarang() {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("kode_barang");
        tabel.addColumn("nama_barang");
        tabel.addColumn("harga");
        tabel.addColumn("satuan");
        tabel.addColumn("stok");
        
         try {
            sql="select * from barang";
            stat= con.createStatement();
            rs= stat.executeQuery(sql);
            while (rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4),
                    rs.getString(5)
                });
                tabelbarang.setModel(tabel);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error"+e);
        }
    }
}
