/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajar;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class pelanggan extends javax.swing.JFrame {
public Connection con;
public ResultSet rs;
public Statement stat;
public String sql="";
    /**
     * Creates new form pelanggan
     */
    public pelanggan() {
        initComponents();
           koneksi db =new koneksi();
        db.koneksi();
        con=db.con;
        rs=db.rs;
        stat=db.stat;
        tampiltabelpelanggan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DATAPELANGGAN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TELEPON = new javax.swing.JLabel();
        KODEPELANGGAN = new javax.swing.JLabel();
        NAMAPELANGGAN = new javax.swing.JLabel();
        ALAMATPELANGGAN = new javax.swing.JLabel();
        Ttelppelanggan = new javax.swing.JTextField();
        Tnamapelanggan = new javax.swing.JTextField();
        Talamat = new javax.swing.JTextField();
        EXIT = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpelanggan = new javax.swing.JTable();
        Tkodepelanggan = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DATAPELANGGAN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DATAPELANGGAN.setText("DATA PELANGGAN");
        jPanel1.add(DATAPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, -1));

        TELEPON.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TELEPON.setForeground(new java.awt.Color(255, 255, 255));
        TELEPON.setText("TELEPON");
        jPanel1.add(TELEPON, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        KODEPELANGGAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KODEPELANGGAN.setForeground(new java.awt.Color(255, 255, 255));
        KODEPELANGGAN.setText("KODE PELANGGAN");
        jPanel1.add(KODEPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        NAMAPELANGGAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NAMAPELANGGAN.setForeground(new java.awt.Color(255, 255, 255));
        NAMAPELANGGAN.setText("NAMA PELANGGAN");
        jPanel1.add(NAMAPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        ALAMATPELANGGAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ALAMATPELANGGAN.setForeground(new java.awt.Color(255, 255, 255));
        ALAMATPELANGGAN.setText("ALAMAT PELANGGAN");
        jPanel1.add(ALAMATPELANGGAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel1.add(Ttelppelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 30));
        jPanel1.add(Tnamapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, 30));
        jPanel1.add(Talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 30));

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 80, 40));

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 40));

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 80, 40));

        EDIT.setText("UPDATE");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });
        jPanel1.add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 40));

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 80, 40));

        tabelpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpelanggan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 570, 120));
        jPanel1.add(Tkodepelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, 30));

        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, 40));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\website pertama\\projek membuat web statis sendiri\\web coba-coba\\wisata2.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
try {
     sql ="insert into pelanggan values('"+
             Tkodepelanggan.getText()+"','"+
             Tnamapelanggan.getText()+"','"+
             Talamat.getText()+"','"+
             Ttelppelanggan.getText()+"')";
         stat=con.createStatement();
            stat.execute(sql);
        Tkodepelanggan.setText("");
        Tnamapelanggan.setText("");
        Talamat.setText("");
        Ttelppelanggan.setText("");
        JOptionPane.showMessageDialog(rootPane, "Data Telah Disimpan");
    } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan, Tidak dapat duplicate data");
        } 
      tampiltabelpelanggan();        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
    try{
        sql="delete from pelanggan  where kodepelanggan='"+
                Tkodepelanggan.getText()+"'";
        stat=con.createStatement();
        stat.execute(sql);
        Tkodepelanggan.setText("");
        Tnamapelanggan.setText("");
        Talamat.setText("");
        Ttelppelanggan.setText("");
        JOptionPane.showMessageDialog(rootPane, "data telah dihapus");
    } catch (SQLException | HeadlessException e) {
        JOptionPane.showMessageDialog(rootPane, "data gagal dihapus" +e);
    }
    tampiltabelpelanggan();// TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void tabelpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpelangganMouseClicked
        Tkodepelanggan.setText(tabelpelanggan.getValueAt(tabelpelanggan.getSelectedRow(), 0).toString()); 
        Tnamapelanggan.setText(tabelpelanggan.getValueAt(tabelpelanggan.getSelectedRow(), 1).toString());
        Talamat.setText(tabelpelanggan.getValueAt(tabelpelanggan.getSelectedRow(), 2).toString());
        Ttelppelanggan.setText(tabelpelanggan.getValueAt(tabelpelanggan.getSelectedRow(), 3).toString());// TODO add your handling code here:
    }//GEN-LAST:event_tabelpelangganMouseClicked

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
 try {
        sql="update pelanggan set kodepelanggan='"+
                Tkodepelanggan.getText()+"',namapelanggan='"+
                Tnamapelanggan.getText()+"',alamatpelanggan='"+
                Talamat.getText()+"' where telp='"+
                Ttelppelanggan.getText()+"'";
        stat=con.createStatement();
        stat.execute(sql);
        JOptionPane.showMessageDialog(rootPane, "data telah di edit");
    }  catch (SQLException | HeadlessException e) {
       JOptionPane.showMessageDialog(rootPane, "data gagal di edit" + e);
    }
        tampiltabelpelanggan(); 
    }//GEN-LAST:event_EDITActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
try {
    sql = "SELECT * FROM pelanggan WHERE kodepelanggan=?";
    ResultSet rs;
    try (PreparedStatement stmt = con.prepareStatement(sql)) {
        stmt.setString(1, Tkodepelanggan.getText());
        rs = stmt.executeQuery();
        if (rs.next()) {
            Tkodepelanggan.setText(rs.getString("kodepelanggan"));
            Tnamapelanggan.setText(rs.getString("namapelanggan"));
            Talamat.setText(rs.getString("alamatpelanggan"));
            Ttelppelanggan.setText(rs.getString("telp"));
            JOptionPane.showMessageDialog(rootPane, "Ini datanya");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
        }
    }
} catch (SQLException | HeadlessException e) {
    JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan: " + e.getMessage());
}
       // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
     Tkodepelanggan.setText("");
     Tnamapelanggan.setText("");
     Talamat.setText("");
     Ttelppelanggan.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMATPELANGGAN;
    private javax.swing.JLabel DATAPELANGGAN;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel KODEPELANGGAN;
    private javax.swing.JLabel NAMAPELANGGAN;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SEARCH;
    private javax.swing.JLabel TELEPON;
    private javax.swing.JTextField Talamat;
    private javax.swing.JTextField Tkodepelanggan;
    private javax.swing.JTextField Tnamapelanggan;
    private javax.swing.JTextField Ttelppelanggan;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelpelanggan;
    // End of variables declaration//GEN-END:variables

    private void tampiltabelpelanggan() {
         DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Kode Pelanggan");
        tabel.addColumn("Nama Pelanggan");
        tabel.addColumn("Alamat");
        tabel.addColumn("NO. HP");
        
         try {
            sql="select * from pelanggan";
            stat= con.createStatement();
            rs= stat.executeQuery(sql);
            while (rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4),
                });
                tabelpelanggan.setModel(tabel);
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error"+e);
        }
    }
}

